config/routes.rb
Rails.application.routes.draw do
  # get 'categorys/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'tests#index'

  # ゲストログイン 購入1 出品2
  post '/guest', to: 'guest_sessions#create'
  post '/guest2', to: 'guest_sessions#create2'

  resources :categorys, only: [:new,:show,:index]
  resources :brands, only: [:show]

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
    get 'creditcards', to: 'users/registrations#new_creditcard'
    post 'creditcards', to: 'users/registrations#create_creditcard'
    get 'profile_edit', to: 'users/registrations#profile_edit'
    patch 'profile_update', to: 'users/registrations#profile_update'
  end
  resources :tests, only: [:index, :new] do
    collection do
      get 'test'
    end
  end
  resources :users, only: [:show,:destroy]


  resources :items do
    resources :favorites, only: [:index,:create,:destroy]
    resources :comments, only: :create
    collection do
      post 'purchase'
      get 'search'
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }

    end
  end


  namespace :item do
    resources :secound, only: [:index ,:show] do
      member do
        get 'sold'
        get 'bought'
      end
    end
  end


  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end

  resources :purchase, only: [:index] do
    member do
      post 'index', to: 'purchase#index'
      post 'pay', to: 'purchase#pay'
      get 'done', to: 'purchase#done'
    end
  end

  resources :addresses, only: [:edit, :update]


end

app/models/address.rb
class Address < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :user, optional: true
  belongs_to_active_hash :prefecture
  validates :name, :name_kana, :postal_code, :prefecture, :city, :address, presence: true

end

app/models/brand.rb
class Brand < ActiveHash::Base
  # has_many :items

  self.data = [
      {id: 1, name: 'アー ヴェ ヴェ'}, {id: 2, name: 'アーカー'}, {id: 3, name: 'アシックス'},
      {id: 4, name: 'アディダス'}, {id: 5, name: 'アトモスガール'}, {id: 6, name: 'アレクサンダーオルチ'},
      {id: 7, name: 'イーストウエスト'}, {id: 8, name: 'イーストランド'}, {id: 9, name: 'イヴ サン ローラン'},
      {id: 10, name: 'イエスタデイズトゥモロー'}, {id: 11, name: 'イグニス'}, {id: 12, name: '一澤帆布'},
      {id: 13, name: 'イルビゾンテ'}, {id: 14, name: 'インケース'}, {id: 15, name: 'ヴィアリパブリカ'},
      {id: 16, name: 'ヴィヴィアン ウエストウッド'}, {id: 17, name: 'ヴィクトリアンメイデン'}, {id: 18, name: 'ヴィドヴァンスター'},
      {id: 19, name: 'ウィリアム ウォレス'}, {id: 20, name: 'ウィリアム・ギブスン'}, {id: 21, name: 'エアリスト'},
      {id: 22, name: 'エアロポステール'}, {id: 23, name: 'エーフィールド'}, {id: 24, name: 'エクリア'},
      {id: 25, name: 'エスアンドエイチ'}, {id: 26, name: 'エヌアイビー'}, {id: 27, name: 'エムエックスピー'},
      {id: 28, name: 'エリオットマン'}, {id: 29, name: 'エルニドフリップス'}, {id: 30, name: 'オーバーザワン'},
      {id: 31, name: 'オーレット'}, {id: 32, name: 'オリーチェ'}, {id: 33, name: '快晴堂'},
      {id: 34, name: 'カシオペア'}, {id: 35, name: 'カマイウ'}, {id: 36, name: 'カルティエ'},
      {id: 37, name: 'カルディ'}, {id: 38, name: 'ガガミラノ'}, {id: 39, name: 'キャトル'},
      {id: 40, name: 'キャドバリー'}, {id: 41, name: 'キルシティ'}, {id: 42, name: 'ギャルリー ヴィー'},
      {id: 43, name: 'クイーン ケリー'}, {id: 44, name: 'クーポール'}, {id: 45, name: 'クプクプ'},
      {id: 46, name: 'クリスティーニューヨーク'}, {id: 47, name: 'グッディグラムス'}, {id: 48, name: 'その他'}
  ]
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user, optional: true
  # validates :card_number, :card_company, :card_year, :card_month,:card_pass, presence: true

  #   enum card_company:{
  #     VISA:1,Mastercard:2,セゾンカード:3,JCB:4,アメリカンエキスプレス:5,ダイナーズ:6,ディスカバー:7
  #   }
end

app/models/category.rb
class Category < ApplicationRecord
  has_ancestry
  has_many :items
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :item, optional: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
extend ActiveHash::Associations::ActiveRecordExtensions
  validates :name, :price, :introduce, :category_id, :commodity_condition_id, :shipping_charge_id, :shipping_method_id,:prefecture_id, :shipping_day_id, presence: true
  belongs_to :buyer, class_name: 'User', :foreign_key => 'buyer_id'
  belongs_to :seller, class_name: 'User', :foreign_key => 'seller_id'
  belongs_to :category
  has_many :item_images, dependent: :destroy
  has_many :favorites
  has_many :users, through: :favorites
  has_many :comments, dependent: :destroy

  belongs_to_active_hash :prefecture
  belongs_to_active_hash :brand
  belongs_to_active_hash :commodity_condition
  belongs_to_active_hash :shipping_day
  belongs_to_active_hash :shipping_method
  belongs_to_active_hash :shipping_charge
  belongs_to_active_hash :size
  accepts_nested_attributes_for :item_images, allow_destroy: true

  def self.search(search)
    return Item.all unless search
    Item.where('name LIKE(?)', "%#{search}%")
  end


  # def self.search(search)
  #   if search
  #     Item.where('text LIKE(?)', "%#{search}%")
  #   else
  #     Item.all
  #   end
  # end
end

app/models/item_image.rb
class ItemImage < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :item, optional: true
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
      {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '岩手県'},
      {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, {id: 6, name: '山形県'},
      {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, {id: 9, name: '栃木県'},
      {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, {id: 12, name: '千葉県'},
      {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, {id: 15, name: '新潟県'},
      {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, {id: 18, name: '福井県'},
      {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, {id: 21, name: '岐阜県'},
      {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, {id: 24, name: '三重県'},
      {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, {id: 27, name: '大阪府'},
      {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, {id: 30, name: '和歌山県'},
      {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, {id: 33, name: '岡山県'},
      {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, {id: 36, name: '徳島県'},
      {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, {id: 39, name: '高知県'},
      {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},
      {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
      {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
  ]
end

app/models/shipping_charge.rb
class ShippingCharge < ActiveHash::Base
  self.data = [
    {id: 1, value: '着払い(落札者負担)'},
    {id: 2, value: '送料込み(出品者負担)'}
  ]
end

app/models/shipping_day.rb
class ShippingDay < ActiveHash::Base
  self.data = [
    {id: 1, value: '1~2日'},
    {id: 2, value: '2~3日'},
    {id: 3, value: '4~7日'}
]
end

app/models/shipping_method.rb
class ShippingMethod < ActiveHash::Base
  self.data = [
    {id: 1, value: '未定'},
    {id: 2, value: 'ゆうパック'},
    {id: 3, value: 'ゆうパケット'},
    {id: 4, value: 'レターパック'},
    {id: 5, value: '普通郵便(定形,定形外)'},
    {id: 6, value: 'クロネコヤマト'},
    {id: 7, value: 'クリックポスト'}
]
end

app/models/size.rb
class Size < ActiveHash::Base
  self.data = [
    {id: 1, value: 'XS以下'},
    {id: 2, value: 'S'},
    {id: 3, value: 'M'},
    {id: 4, value: 'L'},
    {id: 5, value: 'LL'},
    {id: 6, value: '3L'},
    {id: 7, value: '4L以上'},
    {id: 8, value: 'その他'}
  ]
end

app/models/test.rb
class Test < ApplicationRecord



end

app/models/user.rb
class User < ApplicationRecord
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  # mount_uploader :image, ImageUploader

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :nickname, :first_name, :last_name, :first_name_kana, :last_name_kana, :birthday, presence: true
  mount_uploader :image, ImageUploader

  has_one :address
  has_one :card
  has_many :buyer_transactions, class_name: 'Transaction', :foreign_key => 'buyer_id'
  has_many :seller_transactions, class_name: 'Transaction', :foreign_key => 'seller_id'
  has_many :favorites, dependent: :destroy
  has_many :items, through: :favorites
  has_many :comments,  dependent: :destroy
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/card_helper.rb
module CardHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FreemarketSample71a
    %script{src: "https://js.pay.jp/", type: "text/javascript"}
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'shared/header'
    = render 'layouts/notifications'
    = yield
    = render 'shared/footer'

app/views/shared/_footer.html.haml
%footer.footer
  .footer__contents
    %ul.footer-items
      %li.footer-item
        %h2.footer-item__title
          FURIMAについて
        %ul.footer-item__lists
          %li.footer-item__lists__list
            = link_to "/", class: "footer-item__lists__list__link" do
              会社概要（運営会社）
          %li.footer-item__lists__list
            = link_to "/", class: "footer-item__lists__list__link" do
              プライバシーポリシー
          %li.footer-item__lists__list
            = link_to "/", class: "footer-item__lists__list__link" do
              FURIMA利用規約
          %li.footer-item__lists__list
            = link_to "/", class: "footer-item__lists__list__link" do
              ポイントに関する特約
      %li.footer-item
        %h2.footer-item__title
          FURIMAを見る
        %ul.footer-item__lists
          %li.footer-item__lists__list
            = link_to "/", class: "footer-item__lists__list__link" do
              カテゴリー一覧
          %li.footer-item__lists__list
            = link_to "/", class: "footer-item__lists__list__link" do
              ブランド一覧
      %li.footer-item
        %h2.footer-item__title
          ヘルプ＆ガイド
        %ul.footer-item__lists
          %li.footer-item__lists__list
            = link_to "/", class: "footer-item__lists__list__link" do
              FURIMAガイド
          %li.footer-item__lists__list
            = link_to "/", class: "footer-item__lists__list__link" do
              FURIMAロゴ利用ガイドライン
          %li.footer-item__lists__list
            = link_to "/", class: "footer-item__lists__list__link" do
              お知らせ
  .footer__logos
    .footer__logos__logo
      = link_to "/", class: "logo-link" do
        = image_tag 'material/logo/logo-white.png', alt: 'logo', class: 'logo-link__white-img'
    %p.footer__logos__text
      © FURIMA

app/views/shared/_gretel.html.haml
.gretel
  %ul.gretel__lists
    %li.gretel__lists__list
      = breadcrumbs pretext: "",separator: " &rsaquo; ", class: "breadcrumbs-list"

app/views/shared/_header.html.haml
%header.header
  .header-contents
    .header-contents__main
      %h1.icon
        = link_to root_path, class: "icon__link" do
          = image_tag 'material/logo/logo.png', alt:'main-icon', class: 'main-icon'
      .header-form-box
        = form_tag(search_items_path, method: :get ,class:'form') do
          = text_field_tag :keyword, "", {class: "search-fild"}
          = button_tag type: :submit, class: "search-btn" do
            = image_tag 'material/icon/icon-search 1.png',class:"search-icon"
    %nav.header-nav
      .header-nav__left
        .header-nav__left__item
          .add_Anime_atag
            = link_to "#", class: "header-nav-link brand" do
              ブランド
          %ul.brand-lists
            - @brands.each.with_index(1) do |brand,i|
              %li.brand-list
                = link_to brand_path(brand), class: "brand-list__link" do
                  = brand.name
        .header-nav__left__item
          .category_list
            .add_Anime_atag
              = link_to "#", class: "header-nav-link" do
                カテゴリー
            %ul.parents_list
              - @parents.each do |parent|
                %li
                  = link_to  "/categorys/#{parent.id}", class: "parent_category display-none",id: "#{parent.id}" do
                    #{parent.name}
            .children_list

            .grand_children_list

      %ul.header-nav__right.add_Anime_atag

        - if user_signed_in?
          %li.header-nav__right__item
            = link_to  user_path(current_user), class: "header-nav-link" do
              マイページ
          %li.header-nav__right__item
            = link_to items_path, class: "header-nav-link" do
              商品一覧
          %li.header-nav__right__item
            = link_to item_favorites_path(current_user), class: "header-nav-link" do
              お気に入りリスト
        - unless user_signed_in?
          %li.header-nav__right__item
            = link_to new_user_session_path, class: "header-nav-link" do
              ログイン
          %li.header-nav__right__item
            = link_to new_user_registration_path, class: "header-nav-link" do
              新規会員登録

app/views/shared/_item.html.haml
.item-share
  = link_to item_path(item), class: "" do
    .item-share__image
      = image_tag item.item_images[0].image.url , alt: "商品画像", class: "",size: "187x187"
      - if item.purchase_id == 1
        .sold-label
          Sold Out
    .item-share__bottom
      %span.item-share__bottom__title
        =item.name
        .item-share__bottom__title__hidden-box
    .item-share__price
      %p.yen-logo ¥
      = item.price