config/routes.rb
Rails.application.routes.draw do
  # get 'categorys/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'tests#index'

  # ゲストログイン 購入1 出品2
  post '/guest', to: 'guest_sessions#create'
  post '/guest2', to: 'guest_sessions#create2'

  resources :categorys, only: [:new,:show,:index]
  resources :brands, only: [:show]

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
    get 'creditcards', to: 'users/registrations#new_creditcard'
    post 'creditcards', to: 'users/registrations#create_creditcard'
    get 'profile_edit', to: 'users/registrations#profile_edit'
    patch 'profile_update', to: 'users/registrations#profile_update'
  end
  resources :tests, only: [:index, :new] do
    collection do
      get 'test'
    end
  end
  resources :users, only: [:show,:destroy]


  resources :items do
    resources :favorites, only: [:index,:create,:destroy]
    resources :comments, only: :create
    collection do
      post 'purchase'
      get 'search'
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }

    end
  end


  namespace :item do
    resources :secound, only: [:index ,:show] do
      member do
        get 'sold'
        get 'bought'
      end
    end
  end


  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end

  resources :purchase, only: [:index] do
    member do
      post 'index', to: 'purchase#index'
      post 'pay', to: 'purchase#pay'
      get 'done', to: 'purchase#done'
    end
  end

  resources :addresses, only: [:edit, :update]


end

app/controllers/purchase_controller.rb
class PurchaseController < ApplicationController
  require 'payjp'

  def index
    @item = Item.find(params[:id])
    card = Card.where(user_id: current_user.id).first
    #Cardテーブルは前回記事で作成、テーブルからpayjpの顧客IDを検索
    if card.blank?
      #登録された情報がない場合にカード登録画面に移動
      redirect_to controller: "card", action: "new"
    else
      Payjp.api_key = Rails.application.secrets.payjp_private_key
      #保管した顧客IDでpayjpから情報取得
      customer = Payjp::Customer.retrieve(card.customer_id)
      #保管したカードIDでpayjpから情報取得、カード情報表示のためインスタンス変数に代入
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
  end

  def pay
    @item = Item.find(params[:id])
    # @item.purchase_id = 1 #購入済みに数字(1)を入れる
    # @item.buyer_id = current_user.id #購入者代入
    card = Card.where(user_id: current_user.id).first
    # Payjp.api_key = ENV['PAYJP_PRIVATE_KEY']
    Payjp.api_key = Rails.application.secrets.payjp_private_key
    Payjp::Charge.create(
    :amount => @item.price, #支払金額を入力（itemテーブル等に紐づけても良い）
    :customer => card.customer_id, #顧客ID
    :currency => 'jpy', #日本円
    )
    # redirect_to action: 'done' #完了画面に移動
    # @item.save
    @item.update(purchase_id: 1, buyer_id: current_user.id)
    redirect_to done_purchase_path(@item) #完了画面に移動
  end
  
  def done
    @item = Item.find(params[:id])
  end

end

app/helpers/purchase_helper.rb
module PurchaseHelper
end

app/views/purchase/done.html.haml
.card-done
  %h1購入決済完了しました！

  %h3 商品名：#{@item.name}
  %h3 価格：¥#{@item.price}(送料込み)
  = link_to root_path ,class:'btn' do
    %button.submit-btn 商品一覧へ戻る
  = link_to 'https://pay.jp/d/charges',class:'btn' do
    %button.submit-btn pay.jp

app/views/purchase/index.html.haml
.card-index
  %h2 購入を確定しますか？
  %p #{@item.name}
  %p ¥#{@item.price}(送料込み)
  %br
  %h3 支払い方法
  - if @default_card_information.blank?
    %br /
  - else
    -#以下カード情報を表示
    = "**** **** **** " + @default_card_information.last4
    - exp_month = @default_card_information.exp_month.to_s
    - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
    = exp_month + " / " + exp_year
  %br
  -# = form_tag(action: :pay, method: :post,) do
  = form_tag pay_purchase_path(@item),class:'',method: :post do
    %button.submit-btn 購入する