config/routes.rb
Rails.application.routes.draw do
  # get 'categorys/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'tests#index'

  # ゲストログイン 購入1 出品2
  post '/guest', to: 'guest_sessions#create'
  post '/guest2', to: 'guest_sessions#create2'

  resources :categorys, only: [:new,:show,:index]
  resources :brands, only: [:show]

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
    get 'creditcards', to: 'users/registrations#new_creditcard'
    post 'creditcards', to: 'users/registrations#create_creditcard'
    get 'profile_edit', to: 'users/registrations#profile_edit'
    patch 'profile_update', to: 'users/registrations#profile_update'
  end
  resources :tests, only: [:index, :new] do
    collection do
      get 'test'
    end
  end
  resources :users, only: [:show,:destroy]


  resources :items do
    resources :favorites, only: [:index,:create,:destroy]
    resources :comments, only: :create
    collection do
      post 'purchase'
      get 'search'
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }

    end
  end


  namespace :item do
    resources :secound, only: [:index ,:show] do
      member do
        get 'sold'
        get 'bought'
      end
    end
  end


  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end

  resources :purchase, only: [:index] do
    member do
      post 'index', to: 'purchase#index'
      post 'pay', to: 'purchase#pay'
      get 'done', to: 'purchase#done'
    end
  end

  resources :addresses, only: [:edit, :update]


end

app/models/item.rb
class Item < ApplicationRecord
extend ActiveHash::Associations::ActiveRecordExtensions
  validates :name, :price, :introduce, :category_id, :commodity_condition_id, :shipping_charge_id, :shipping_method_id,:prefecture_id, :shipping_day_id, presence: true
  belongs_to :buyer, class_name: 'User', :foreign_key => 'buyer_id'
  belongs_to :seller, class_name: 'User', :foreign_key => 'seller_id'
  belongs_to :category
  has_many :item_images, dependent: :destroy
  has_many :favorites
  has_many :users, through: :favorites
  has_many :comments, dependent: :destroy

  belongs_to_active_hash :prefecture
  belongs_to_active_hash :brand
  belongs_to_active_hash :commodity_condition
  belongs_to_active_hash :shipping_day
  belongs_to_active_hash :shipping_method
  belongs_to_active_hash :shipping_charge
  belongs_to_active_hash :size
  accepts_nested_attributes_for :item_images, allow_destroy: true

  def self.search(search)
    return Item.all unless search
    Item.where('name LIKE(?)', "%#{search}%")
  end


  # def self.search(search)
  #   if search
  #     Item.where('text LIKE(?)', "%#{search}%")
  #   else
  #     Item.all
  #   end
  # end
end

app/controllers/item/secound_controller.rb
class Item::SecoundController < ApplicationController
before_action :buyer?, only: [:show]
before_action :configure_sign_up_params, only: [:create]

  def index

  end

  def show
    @item = Item.find(params[:id])

    # pay.jpのカード参照用記述
    @card = Card.where(user_id: current_user.id).first
    if @card.blank?
    #   redirect_to new_card_path
    else
      Payjp.api_key = Rails.application.secrets.payjp_private_key
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @default_card_information = customer.cards.retrieve(@card.card_id)
    end
  end

  def bought
    @items = Item.where(buyer_id: params[:id],purchase_id:1)
  end

  def sold
    @user = User.find(params[:id])
    @items = Item.where(seller_id: @user)
  end

  def buyer?
    @item = Item.find(params[:id])
    redirect_to item_path(@item) if current_user.id == @item.seller_id
  end


end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  require 'payjp'
  before_action :seller?, only: [:destroy, :edit]

  def index
    @items = Item.where(purchase_id: nil)
    @parents = Category.all.order("id ASC").limit(13)

  end

  def show
    @item = Item.find(params[:id])
    @category = @item.category
    if @category.parent.present?
      @parent = @category.parent
      if @parent.parent.present?
        @grandparent = @parent.parent
      end
    end

    @user = User.find(@item.seller_id)
    @my_items = Item.where(seller_id: @item.seller_id)
    @comment = Comment.new
    @comments = @item.comments.includes(:user)
  end

  def new
    @item = Item.new
    @item.item_images.new
  end

  def create
    @item = Item.new(item_params)
    unless @item.valid?
      flash[:alert] = "必須項目を確認してください"
      redirect_to new_item_path and return
    end
    @item.save
    flash[:notice] = "出品が完了しました"
    redirect_to root_path and return
  end

  def edit
    @item = Item.find(params[:id])
    if @item.seller_id == current_user.id
      
    else
      redirect_to root_path
    end
  end

  def update
    # 勉強用に残してね

    # binding.pry
    @item = Item.find(params[:id])
    # @new_item = Item.new(item_update_params)
    # unless @new_item.valid?
    #   flash[:alert] = "必須項目を確認してください"
    #   redirect_to edit_item_path and return
    # end
    if @item.update(item_params)
    flash[:notice] = "編集が完了しました"
    redirect_to root_path and return
    else
      flash[:alert] = "必須項目を確認してください"
      redirect_to edit_item_path and return
    end
  end

  def destroy
    @item =Item.find(params[:id])

    if @item.destroy
      flash[:notice] = "商品を削除しました"
      redirect_to root_path
    else
      redirect_to item_path(@item)
    end
  end

  def get_category_children
    @category_children = Category.find_by(id: params[:parent_id], ancestry: nil).children
  end

  def get_category_grandchildren
      @category_grandchildren = Category.find(params[:child_id]).children
  end

  def search
    @items = Item.search(params[:keyword])
  end

  def seller?
    @item = Item.find(params[:id])
    redirect_to root_path unless current_user.id == @item.seller_id
  end

  private

  def item_params
    params.require(:item).permit(:name, :price, :introduce, :brand_id, :category_id, :size_id, :commodity_condition_id, :shipping_charge_id, :shipping_method_id,:prefecture_id, :shipping_day_id, item_images_attributes: [:image, :_destroy, :id]).merge(seller_id: current_user.id).merge(buyer_id: current_user.id)
  end

  def item_update_params
    params.require(:item).permit(:name, :price, :introduce, :brand_id, :size_id, :category_id, :commodity_condition_id, :shipping_charge_id, :shipping_method_id,:prefecture_id, :shipping_day_id, item_images_attributes: [:image, :_destroy, :id]).merge(seller_id: current_user.id).merge(buyer_id: current_user.id)
  end

  def purchase

    Payjp.api_key = ""
    Payjp::Charge.create(
      amount: 111,
      card: params['payjp-token'],
      currency: 'jpy'
    )
    redirect_to root_path, notice: "支払いが完了しました"
  end

end

app/helpers/item/secound_helper.rb
module Item::SecoundHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.haml
.i-n
  .i-n__inner
    = form_for @item do |f|
      .i-n-image
        .i-n-image__inner
          .teams
            %h3.i-n-team
              出品画像
            %p.hissu
              必須
          .i-n-image__inner__container
            .prev-content
              - @item.item_images.each do |image|
                .preview-box
                  .upper-box
                    = image_tag image.image.url, alt: "preview"
                  .lower-box
                    .delete-box
                      .delete-btn
                        %span 削除
            .label-content
              %label{for: "item_item_images_attributes_#{@item.item_images.length}_image", class: "label-box", id: "label-box--#{@item.item_images.length}"}
                %pre.label-box__text-visible クリックしてファイルをアップロード
              %p 最大5枚までアップロードできます
            .hidden-content

              = f.fields_for :item_images do |i|
                = i.file_field :image, class: "hidden-field"
                - if @item.persisted?
                  = i.check_box:_destroy, class: "hidden-checkbox"
                - @item.item_images.length.upto(5) do |n|
                  %input{ class: "hidden-field", name: "item[item_images_attributes][#{n}][image]", id: "item_item_images_attributes_#{n}_image", type:"file"}

      .i-n-names
        .i-n-names__inner
          .i-n-names__inner__name
            .teams
              %h3.i-n-team
                商品名
              %p.hissu
                必須
            = f.text_field :name, placeholder: "40文字まで", class: 'form-content'
          .i-n-names__inner__text
            .teams
              %h3.i-n-team
                商品の説明
              %p.hissu
                必須
            = f.text_area :introduce,lows: "50",cols: "8", placeholder: "商品の説明", class: 'form-content text-area'
      .i-n-categories
        .i-n-categories__inner
          .i-n-categories__inner__category
            .teams
              %h3.i-n-team
                カテゴリー
              %p.hissu
                必須
            .category-contents
              .cattegory-contents__inner
                = f.collection_select :category_id, Category.where(ancestry: nil), :id, :name,{}, class: 'form-content--select'
          .i-n-categories__inner__brand
            .teams
              %h3.i-n-team
                ブランド
              %p.not_hissu
                任意
            = f.collection_select :brand_id, Brand.all, :id, :name,{ include_blank: '選択してください' }, class: 'form-content--select'
          .i-n-categories__inner__condition
            .teams
              %h3.i-n-team
                商品の状態
              %p.hissu
                必須
            = f.collection_select :commodity_condition_id, CommodityCondition.all, :id, :value,{}, class: 'form-content--select'
      .i-n-delivery
        .i-n-delivery__inner
          .i-n-delivery__inner__method
            .teams
              %h3.i-n-team
                配送
              %p.hissu
                必須
            = f.collection_select :shipping_method_id, ShippingMethod.all, :id, :value,{}, class: 'form-content--select'
          .i-n-delivery__inner__charge
            .teams
              %h3.i-n-team
                配送料の負担
              %p.hissu
                必須
            = f.collection_select :shipping_charge_id, ShippingCharge.all, :id, :value,{}, class: 'form-content--select'
          .i-n-delivery__inner__prefecture
            .teams
              %h3.i-n-team
                発送元の地域
              %p.hissu
                必須
            = f.collection_select :prefecture_id, Prefecture.all, :id, :name,{}, class: 'form-content--select'
          .i-n-delivery__inner__day
            .teams
              %h3.i-n-team
                発送までの日数
              %p.hissu
                必須
            = f.collection_select :shipping_day_id, ShippingDay.all, :id, :value,{}, class: 'form-content--select'
      .i-n-prices
        .i-n-prices__inner
          .i-n-prices__inner__price
            .teams.teams-price
              %h3.i-n-team
                販売価格
              %p.hissu
                必須
            = f.number_field :price, placeholder: "0", class: 'form-content num-form'
      .i-n-submit
        .i-n-submit__inner
          = f.submit "更新する", class: 'form-submit hidden-btn'

app/views/items/index.html.haml
- breadcrumb :all_items
= render "shared/gretel"
.i-i
  .inner
    %h2.heading
      商品一覧
  .form
    = render partial: 'shared/item', collection: @items

app/views/items/new.html.haml
- breadcrumb :new_item
= render "shared/gretel"
.i-n
  .i-n__inner
    = form_for @item do |f|
      .i-n-image
        .i-n-image__inner
          .teams
            %h3.i-n-team
              出品画像
            %p.hissu
              必須
          .i-n-image__inner__container
            .prev-content
            .label-content
              %label{for: "item_item_images_attributes_0_image", class: "label-box", id: "label-box--0"}
                %pre.label-box__text-visible クリックしてファイルをアップロード
                %p 最大5枚までアップロードできます
            .hidden-content
              = f.fields_for :item_images do |i|
                = i.file_field :image, class:"hidden-field"
                %input{class:"hidden-field", type: "file", name: "item[item_images_attributes][1][image]", id: "item_item_images_attributes_1_image" }
                %input{class:"hidden-field", type: "file", name: "item[item_images_attributes][2][image]", id: "item_item_images_attributes_2_image" }
                %input{class:"hidden-field", type: "file", name: "item[item_images_attributes][3][image]", id: "item_item_images_attributes_3_image" }
                %input{class:"hidden-field", type: "file", name: "item[item_images_attributes][4][image]", id: "item_item_images_attributes_4_image" }
      .i-n-names
        .i-n-names__inner
          .i-n-names__inner__name
            .teams
              %h3.i-n-team
                商品名
              %p.hissu
                必須
            = f.text_field :name, placeholder: "40文字まで", class: 'form-content'
          .i-n-names__inner__text
            .teams
              %h3.i-n-team
                商品の説明
              %p.hissu
                必須
            = f.text_area :introduce,lows: "50",cols: "8", placeholder: "商品の説明", class: 'form-content text-area'
      .i-n-categories
        .i-n-categories__inner
          .i-n-categories__inner__category
            .teams
              %h3.i-n-team
                カテゴリー
              %p.hissu
                必須
            .category-contents
              .cattegory-contents__inner
                = f.collection_select :category_id,Category.where(ancestry: nil), :id, :name,{ include_blank: '選択してください' }, class: 'form-content--select'
          .i-n-categories__inner__brand
            .teams
              %h3.i-n-team
                ブランド
              %p.not_hissu
                任意
            = f.collection_select :brand_id, Brand.all, :id, :name,{ include_blank: '選択してください' }, class: 'form-content--select'
          .i-n-categories__inner__condition
            .teams
              %h3.i-n-team
                商品の状態
              %p.hissu
                必須
            = f.collection_select :commodity_condition_id, CommodityCondition.all, :id, :value,{ include_blank: '選択してください' }, class: 'form-content--select'
      .i-n-delivery
        .i-n-delivery__inner
          .i-n-delivery__inner__method
            .teams
              %h3.i-n-team
                配送
              %p.hissu
                必須
            = f.collection_select :shipping_method_id, ShippingMethod.all, :id, :value,{ include_blank: '選択してください' }, class: 'form-content--select'
          .i-n-delivery__inner__charge
            .teams
              %h3.i-n-team
                配送料の負担
              %p.hissu
                必須
            = f.collection_select :shipping_charge_id, ShippingCharge.all, :id, :value,{ include_blank: '選択してください' }, class: 'form-content--select'
          .i-n-delivery__inner__prefecture
            .teams
              %h3.i-n-team
                発送元の地域
              %p.hissu
                必須
            = f.collection_select :prefecture_id, Prefecture.all, :id, :name,{ include_blank: '選択してください' }, class: 'form-content--select'
          .i-n-delivery__inner__day
            .teams
              %h3.i-n-team
                発送までの日数
              %p.hissu
                必須
            = f.collection_select :shipping_day_id, ShippingDay.all, :id, :value,{ include_blank: '選択してください' }, class: 'form-content--select'
      .i-n-prices
        .i-n-prices__inner
          .i-n-prices__inner__price
            .teams.teams-price
              %h3.i-n-team
                販売価格
              %p.hissu
                必須
            = f.number_field :price, placeholder: "0", class: 'form-content num-form'
      .i-n-submit
        .i-n-submit__inner
          = f.submit "出品する", class: 'form-submit hidden-btn'

app/views/items/search.html.haml
.form
  = render partial: 'shared/item', collection: @items

app/views/items/show.html.haml
- breadcrumb :item
= render "shared/gretel"
.inner
  .item-name
    = @item.name
  .top
    .item
      .item__left
        .item__left__mainpic
          = image_tag @item.item_images.first.image.url, alt: "AppStoreで入手", class: "img" ,size: "270x360"
        .item__left__subpic
          - @item.item_images.each do |image|
            .item__left__subpic1__1.subpic
            = image_tag image.image.url, alt: "AppStoreで入手", class: "img1" ,size: "270x360"
      .item__right
        %table
          %tr
            %th
              出品者
            %td
              = @user.nickname
          %tr
            %th
              カテゴリー
            %td
              - if @grandparent.present?
                .category-name
                  = @grandparent.name
              - if @parent.present?
                .category-name
                  = @parent.name
              .category-name
                = @category.name
          %tr
            %th
              ブランド
            %td
              -if @item.brand_id.present?
                = @item.brand.name
          %tr
            %th
              商品の状態
            %td
              = @item.commodity_condition.value
          %tr
            %th
              配送料の負担
            %td
              = @item.shipping_charge.value
          %tr
            %th
              配送の方法
            %td
              = @item.shipping_method.value
          %tr
            %th
              配送元地域
            %td
              = @item.prefecture.name
          %tr
            %th
              配送日の目安
            %td
              = @item.shipping_day.value


  .middle
    .item-explain
      .item-explain__price
        .item-explain__price__num
          ¥
          = @item.price
        .item-explain__price__tax
          (税込)
        .item-explain__price__sendway
          送料込み
      .item-btn-contents
        - if user_signed_in?
          - if current_user.id == @item.seller_id
            =link_to edit_item_path(@item) ,class:"item-explain__link my-item-btn"  do
              .item-explain__link__btn.btn-blue
                編集
            =link_to item_path(@item), method: :delete, class:"item-explain__link my-item-btn"  do
              .item-explain__link__btn
                削除
          - elsif @item.purchase_id == nil
            = link_to item_secound_path ,class:"item-explain__link"  do
              .item-explain__link__btn
                購入画面に進む
          - else
            .sold-btn
              売り切れ
      .item-explain__content
        = @item.introduce
        %br
    .item-explain__under
      .left
    - if user_signed_in?
      - if @item.favorites.exists?(user_id: current_user.id)
        =link_to item_favorite_path(@item) ,class:"item-explain__under__iine",method: :delete do
          .item-explain__under__btn
            %i.far.fa-heart お気に入りを解除する
          =link_to '#' ,class:"item-explain__under__iine"  do
            .item-explain__under__btn
              %i.far.fa-flag 不適切な商品の報告
      - else
        =link_to item_favorites_path(@item) ,class:"item-explain__under__iine",method: :post do
          .item-explain__under__btn
            %i.far.fa-heart お気に入りに登録する
      .right
        =link_to '#' ,class:"item-explain__under__iine"  do
          .item-explain__under__btn
            %i.far.fa-flag  あんしん・あんぜんへの取り組み
  .bottom
    .buyer-profile
      %p.buyer-profile__top
        Buyer :
      .buyer-profile__name
        = link_to user_path(@user), class: "user-page-link" do
          = @user.nickname
    - if user_signed_in?
      .comment
        .comment__attention
          相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。

        =form_for([@item, @comment], local: true) do |form|
          =form.text_area :text, placeholder: "コメントする", rows: "3", class: "comment-field"
          =form.submit "SEND", class:"btn"
    .chat
      %h1.font
        ＜コメント一覧＞
      .chat__comment
        - if @comments
          - @comments.each do |chat|
            .chat__comment__box
              .chat__comment__box__left
                = image_tag 'moduls/makonari.jpg', alt: '社長', class: 'profile-image' ,size: "40x40"
              .chat__comment__box__right
                .chat__comment__box__right__name
                  = link_to chat.user.nickname,"/users/#{chat.user_id}"
                -# .chat__comment__box__right__edit
                -#   = link_to item_comment_path(@comments), method: :delete
                .chat__comment__box__right__text
                  = chat.text
                  .chat__comment__box__right__text__hukidashi

  .social
    %i.fab.fa-facebook-square.fa-4x
    %i.fab.fa-twitter-square.fa-4x
    %i.fab.fa-pinterest-square.fa-4x
    %i.fab.fa-line.fa-4x
.another
  = link_to '#',class: 'text-decolation-none' do
    .another__title
      %p
        = @user.nickname
      %p
        さんの出品一覧
    .items-another

      - @my_items.each do |item|

        = render partial: 'shared/item', locals: {item: item}