config/routes.rb
Rails.application.routes.draw do
  # get 'categorys/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'tests#index'

  # ゲストログイン 購入1 出品2
  post '/guest', to: 'guest_sessions#create'
  post '/guest2', to: 'guest_sessions#create2'

  resources :categorys, only: [:new,:show,:index]
  resources :brands, only: [:show]

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
    get 'creditcards', to: 'users/registrations#new_creditcard'
    post 'creditcards', to: 'users/registrations#create_creditcard'
    get 'profile_edit', to: 'users/registrations#profile_edit'
    patch 'profile_update', to: 'users/registrations#profile_update'
  end
  resources :tests, only: [:index, :new] do
    collection do
      get 'test'
    end
  end
  resources :users, only: [:show,:destroy]


  resources :items do
    resources :favorites, only: [:index,:create,:destroy]
    resources :comments, only: :create
    collection do
      post 'purchase'
      get 'search'
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }

    end
  end


  namespace :item do
    resources :secound, only: [:index ,:show] do
      member do
        get 'sold'
        get 'bought'
      end
    end
  end


  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end

  resources :purchase, only: [:index] do
    member do
      post 'index', to: 'purchase#index'
      post 'pay', to: 'purchase#pay'
      get 'done', to: 'purchase#done'
    end
  end

  resources :addresses, only: [:edit, :update]


end

app/models/item.rb
class Item < ApplicationRecord
extend ActiveHash::Associations::ActiveRecordExtensions
  validates :name, :price, :introduce, :category_id, :commodity_condition_id, :shipping_charge_id, :shipping_method_id,:prefecture_id, :shipping_day_id, presence: true
  belongs_to :buyer, class_name: 'User', :foreign_key => 'buyer_id'
  belongs_to :seller, class_name: 'User', :foreign_key => 'seller_id'
  belongs_to :category
  has_many :item_images, dependent: :destroy
  has_many :favorites
  has_many :users, through: :favorites
  has_many :comments, dependent: :destroy

  belongs_to_active_hash :prefecture
  belongs_to_active_hash :brand
  belongs_to_active_hash :commodity_condition
  belongs_to_active_hash :shipping_day
  belongs_to_active_hash :shipping_method
  belongs_to_active_hash :shipping_charge
  belongs_to_active_hash :size
  accepts_nested_attributes_for :item_images, allow_destroy: true

  def self.search(search)
    return Item.all unless search
    Item.where('name LIKE(?)', "%#{search}%")
  end


  # def self.search(search)
  #   if search
  #     Item.where('text LIKE(?)', "%#{search}%")
  #   else
  #     Item.all
  #   end
  # end
end

app/controllers/item/secound_controller.rb
class Item::SecoundController < ApplicationController
before_action :buyer?, only: [:show]
before_action :configure_sign_up_params, only: [:create]

  def index

  end

  def show
    @item = Item.find(params[:id])

    # pay.jpのカード参照用記述
    @card = Card.where(user_id: current_user.id).first
    if @card.blank?
    #   redirect_to new_card_path
    else
      Payjp.api_key = Rails.application.secrets.payjp_private_key
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @default_card_information = customer.cards.retrieve(@card.card_id)
    end
  end

  def bought
    @items = Item.where(buyer_id: params[:id],purchase_id:1)
  end

  def sold
    @user = User.find(params[:id])
    @items = Item.where(seller_id: @user)
  end

  def buyer?
    @item = Item.find(params[:id])
    redirect_to item_path(@item) if current_user.id == @item.seller_id
  end


end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  require 'payjp'
  before_action :seller?, only: [:destroy, :edit]

  def index
    @items = Item.where(purchase_id: nil)
    @parents = Category.all.order("id ASC").limit(13)

  end

  def show
    @item = Item.find(params[:id])
    @category = @item.category
    if @category.parent.present?
      @parent = @category.parent
      if @parent.parent.present?
        @grandparent = @parent.parent
      end
    end

    @user = User.find(@item.seller_id)
    @my_items = Item.where(seller_id: @item.seller_id)
    @comment = Comment.new
    @comments = @item.comments.includes(:user)
  end

  def new
    @item = Item.new
    @item.item_images.new
  end

  def create
    @item = Item.new(item_params)
    unless @item.valid?
      flash[:alert] = "必須項目を確認してください"
      redirect_to new_item_path and return
    end
    @item.save
    flash[:notice] = "出品が完了しました"
    redirect_to root_path and return
  end

  def edit
    @item = Item.find(params[:id])
    if @item.seller_id == current_user.id
      
    else
      redirect_to root_path
    end
  end

  def update
    # 勉強用に残してね

    # binding.pry
    @item = Item.find(params[:id])
    # @new_item = Item.new(item_update_params)
    # unless @new_item.valid?
    #   flash[:alert] = "必須項目を確認してください"
    #   redirect_to edit_item_path and return
    # end
    if @item.update(item_params)
    flash[:notice] = "編集が完了しました"
    redirect_to root_path and return
    else
      flash[:alert] = "必須項目を確認してください"
      redirect_to edit_item_path and return
    end
  end

  def destroy
    @item =Item.find(params[:id])

    if @item.destroy
      flash[:notice] = "商品を削除しました"
      redirect_to root_path
    else
      redirect_to item_path(@item)
    end
  end

  def get_category_children
    @category_children = Category.find_by(id: params[:parent_id], ancestry: nil).children
  end

  def get_category_grandchildren
      @category_grandchildren = Category.find(params[:child_id]).children
  end

  def search
    @items = Item.search(params[:keyword])
  end

  def seller?
    @item = Item.find(params[:id])
    redirect_to root_path unless current_user.id == @item.seller_id
  end

  private

  def item_params
    params.require(:item).permit(:name, :price, :introduce, :brand_id, :category_id, :size_id, :commodity_condition_id, :shipping_charge_id, :shipping_method_id,:prefecture_id, :shipping_day_id, item_images_attributes: [:image, :_destroy, :id]).merge(seller_id: current_user.id).merge(buyer_id: current_user.id)
  end

  def item_update_params
    params.require(:item).permit(:name, :price, :introduce, :brand_id, :size_id, :category_id, :commodity_condition_id, :shipping_charge_id, :shipping_method_id,:prefecture_id, :shipping_day_id, item_images_attributes: [:image, :_destroy, :id]).merge(seller_id: current_user.id).merge(buyer_id: current_user.id)
  end

  def purchase

    Payjp.api_key = ""
    Payjp::Charge.create(
      amount: 111,
      card: params['payjp-token'],
      currency: 'jpy'
    )
    redirect_to root_path, notice: "支払いが完了しました"
  end

end

app/helpers/item/secound_helper.rb
module Item::SecoundHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/item/secound/bought.html.haml
-# =render partial:'shared/item',locals:{ article:@article }
- breadcrumb :bought_items
= render "shared/gretel"
.t-b
  .inner
    %h2.heading
      購入済み商品
    .form
      - @items.each do |item|
        .item-share
          = link_to item_path(item), class: "" do
            .item-share__image
              = image_tag item.item_images[0].image.url , alt: "商品画像", class: "",size: "187x187"
            .item-share__bottom
              %span.item-share__bottom__title
                =item.name
                .item-share__bottom__title__hidden-box
            .item-share__price
              ¥#{item.price}

app/views/item/secound/show.html.haml
.buypage
  .buypage__header
    = link_to '/' , class: '' do
      = image_tag "material/logo/logo.png", alt: "logo画像", class: "",size: "120x33"
     
  .buypage__main
    .buypage__main__title
      購入内容の確認
    %br
    .buypage__main__item
      .flex
        .buypage__main__item__image
          = link_to '/' , class: 'another-image' do
            = image_tag @item.item_images.first.image.url, alt: "商品画像", class: "image",size: "110x80"
        .buypage__main__item__texts
          .buypage__main__item__texts__title
            #{@item.name}
          .flex2
            .buypage__main__item__texts__price
              ¥#{@item.price}
            .buypage__main__item__texts__send-fee
              （税込）送料込み
      .buypage__main__item__form
        .buypage__main__item__form__price
          .upper
            .buypage__main__item__form__price__label
              支払い金額
            .buypage__main__item__form__price__num
              ¥#{@item.price}

          .bottom
            .buypage__main__item__form__price__point
              ポイントを使用 (所持ポイント: P0)支払い方法
            
        %br
        .buypage__main__item__form__pay-way
          .left
            .buypage__main__item__form__pay-way__name
              支払い方法
            .buypage__main__item__form__pay-way__credit
              クレジットカード
            .buypage__main__item__form__pay-way__logo
              = image_tag "card/visa.svg", alt: "カードロゴ画像", class: "",size: "49x15"
          .right
            .div
              = link_to '変更する', '/', class: 'text-decolation-none'
            %br
            - if @card.blank?
              .div
                カード未登録
            - else
              .div
                = "**** **** **** " + @default_card_information.last4
              .div
                - exp_month = @default_card_information.exp_month.to_s
                - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
                = exp_month + " / " + exp_year

        .buypage__main__item__form__delivery
          .left
            .buypage__main__item__form__delivery__label
              配送先
            .buypage__main__item__form__delivery__address
              %p 〒190-xxxx
              %p 東京都xxxx-xxx-
              %p テック 太郎
          .right
            = link_to '変更する', '/', class: 'text-decolation-none'
        
        .buypage__main__item__form__buy-btn
          = link_to 'カード登録', pay_card_index_path, class: 'buypage__main__item__form__buy-btn'
        .buypage__main__item__form__buy-btn
          = link_to '購入する', purchase_path(@item), class: 'buypage__main__item__form__buy-btn',method: :post

            
  .buy-page__footer
    .buy-page__footer__top
      = link_to 'プライバシーポリシー', '/', class: 'another-link'
    .buy-page__footer__top
      = link_to 'メルカリ利用規約', '/', class: 'another-link'
    .buy-page__footer__top
      = link_to 'メルカリ利用規約', '/', class: 'another-link'
    .buy-page__footer__middle
      = image_tag "material/logo/logo-gray.svg", alt: "ブランドロゴ画像", class: "",size: "85x65"
      
    .buy-page__footer__middle--image
      ©︎Furima, Inc.
    .buy-page__footer__bottom
      

app/views/item/secound/sold.html.haml
-# =render partial:'shared/item',locals:{ article:@article }

.i-s
  .inner
    %h2.heading
      購入済み商品
    .form
      - if @items.present?
        - @items.each do |item|
          = render partial: 'shared/item', locals: {item: item}